### ISSUE TITLE
Fix dependencies in bower.json

### ISSUE THREAD

**Issue by dhardtke** [misantron/datatables-bootstrap3-plugin#1]
Hey,
as of right now we use unofficial repositories for DataTables and FontAwesome:

``` json
"dependencies": {
"bootstrap": "3.3.x",
"components-font-awesome": "4.2.x",
"datatables": "1.10.x"
},
```

It would be much better to use the official ones (for several reasons, one of it would be that I don't have to include FontAwesome twice in my project):

``` json
"dependencies": {
"bootstrap": "3.3.x",
"fontawesome": "4.2.x",
"DataTables": "1.10.x"
},
```

Thanks!

**Comment by misantron** [comment]
Bower.json dependencies fix is ready now, check the laterst release.
Thanks for help.
