### ISSUE TITLE
CommonJS doesn't work.

### ISSUE THREAD

**Issue by EvanCarroll** [misantron/datatables-bootstrap3-plugin#4]
Do you have any examples of getting this to work under CommonJS? When I `require('datatables-bootstrap3-plugin')`, I get an empty object. I get the same thing in phantomjs.

```
phantomjs> require('datatables-bootstrap3-plugin');
{}
```

**Comment by misantron** [comment]
I've made a small code fix. Try to use latest library version (dev-master). Hope it helps your problem.

**Comment by EvanCarroll** [comment]
I think the issue is, just fyi:
1. the factory doesn't return `DataTable` and it should.
2. in the CommonJS UMD piece it's not setting module.exports, and [it should](http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/).

Also, the module should specify `jquery` in the `package.json`.

**Comment by EvanCarroll** [comment]
Where is dev-master? I don't see that branch..

**Comment by misantron** [comment]
No need to specify jquery dependency in package.json because datatables component already do this.

**Comment by EvanCarroll** [comment]
> No need to specify jquery dependency in package.json because datatables component already do this.

If we don't add jQuery to the package.json you'll get an error.

``` text
Error: Cannot find module 'jquery'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /home/ecarroll/code/dt2/node_modules/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js:177
  /home/ecarroll/code/dt2/node_modules/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js:185
  /home/ecarroll/code/dt2/node_modules/datatables-bootstrap3-plugin/media/js/datatables-bootstrap3.js:186
{}
```

We _definitely_ need to require jQuery in our own `package.json`. And, if we want to DataTables to use our expanded jQuery we need to be able to provide that to DataTables in a constructor.

If none of this made sense, just think about this. Relative to our directory we have..

> `node_modules\datatables\node_modules\jquery`

@misantron When we run `require('node_modules')` we don't recurse forward through the whole directory tree. We simply check `./node_modules` and then `../node_modules`, and then `../../node_modules` until we find a directory that exists. If it's not in that directory we give up.. See [this doc](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders). We need this to be in `./node_modules` the way to make that happen is to add it `package.json`.

**Comment by EvanCarroll** [comment]
Just try these things. Get `phantomjs` and try `require('datatables-bootstrap3-plugin')` The whole idea of CommonJS is to be a module system. It wouldn't be a module system if we were relying on the dependencies of our dependency. We need to require a jQuery to call $.ext on, and then we need to supply that to DataTables (if DataTables need to use our modified version). Then we need to return that to the user (via `return` in the factory which needs to set `module.exports`). So the user can do something like..

```
var jQuery = require('datatables-bootstrap3-plugin')..
```

Or, alternatively, we need to something like..

```
var jQuery = require('jquery');
require('datatables-bootstrap3-plugin')(jQuery) // mutates jQuery by calling arguments[0].ext()
```

With the above we wouldn't have to expanding a new jQuery, we would be expanding a version the caller would supply.

**Comment by misantron** [comment]
@EvanCarroll can you please test the latest version?

**Comment by EvanCarroll** [comment]
You're still not returning anything.. Just test it..

``` text
$ npm init -f
$ npm install "https://github.com/misantron/datatables-bootstrap3-plugin"
$ echo "console.log( require('datatables-bootstrap3-plugin') );" > myTest.js
$ phantomjs myTest.js
undefined
```

**Comment by EvanCarroll** [comment]
Ok, I'm going to fork and publish. Need to make this work, not getting feedback and I don't think you understand CommonJS.

**Comment by EvanCarroll** [comment]
You should consider deleting this repo, it's broke and confusing at this point. DataTables/Plugins currently has this same broken code and I'm working to fix it there.

**Comment by misantron** [comment]
It's very strange suggestion - to delete this repo. First of all using with Node.js is not the only way to use this library. It works fine with client side javascript model. Originally this code not intended to be used on server side with Node.js. NPM integration was added later and for someone it works well. If you think this code is broken you can easily make the pull request and fix it. If you don't want to contribute to this repo you can make your own solution. You can do what you want to do. Everything is in your hands. Good luck.

**Comment by EvanCarroll** [comment]
Node integration doesn't work at all. You essentially published to npm and because that's totally broke this code can only ever be used in direct includes. So you can npm install code, and then use it like

```
<script source="//node_modules/datatables-bootstrap3-plugin/js/whatever.js"></script>
```

But you could never `require('datatables-bootstrap3-plugin')`. I've already written it to work, and contacted the author at https://github.com/DataTables/Plugins/issues/199. We're working to fix this in DataTables proper now.

**Comment by EvanCarroll** [comment]
I'm just saying if you want to keep this module up, you should at least consider removing the NPM publication and publishing it to something that doesn't use CommonJS -- like Bower. Since it's essentially a noop right now.
